# Generated by Django 2.0.6 on 2018-08-03 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='qr_map',
            fields=[
                ('unique_num', models.CharField(editable=False, max_length=13, primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=25)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='visit',
            fields=[
                ('visit_id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=25)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.DoctorAccount')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor', to='accounts.HospitalAccount')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='accounts.UserAccount')),
            ],
        ),
    ]
