# Generated by Django 2.0.6 on 2018-08-03 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('initializer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_checkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField()),
                ('comments', models.TextField()),
                ('visit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initializer.visit')),
            ],
        ),
    ]
